services:

  app:
    image: denoland/deno:latest
    restart: unless-stopped
    volumes:
      - ./services/app:/app
    ports:
      - 127.0.0.1:9000:9000
    working_dir: /app
    command: deno task dev